-- Authors data
insert into authors (name) values ('Bernie');
insert into authors (name) values ('Brigg');
insert into authors (name) values ('Lorena');
insert into authors (name) values ('Wynne');
insert into authors (name) values ('Tamqrah');
insert into authors (name) values ('Jim');
insert into authors (name) values ('Wade');
insert into authors (name) values ('Archaimbaud');
insert into authors (name) values ('Caryl');
insert into authors (name) values ('Kayne');
insert into authors (name) values ('Aida');
insert into authors (name) values ('Leland');
insert into authors (name) values ('Birgitta');
insert into authors (name) values ('Kip');
insert into authors (name) values ('Norby');
insert into authors (name) values ('Vito');
insert into authors (name) values ('Hermann');
insert into authors (name) values ('Minnnie');
insert into authors (name) values ('Shelby');
insert into authors (name) values ('Kin');
insert into authors (name) values ('Michaela');
insert into authors (name) values ('Amargo');
insert into authors (name) values ('Jarrett');
insert into authors (name) values ('West');
insert into authors (name) values ('Reggi');
insert into authors (name) values ('Dougie');
insert into authors (name) values ('Jan');
insert into authors (name) values ('Leah');
insert into authors (name) values ('Nolie');
insert into authors (name) values ('Minna');

-- Books data
insert into books (name) values ('Went the Day Well?');
insert into books (name) values ('Mirror Mirror');
insert into books (name) values ('Caiman, The (Il caimano)');
insert into books (name) values ('Rhapsody in August (Hachi-gatsu no kyôshikyoku)');
insert into books (name) values ('Don''t Eat the Pictures: Sesame Street at the Metropolitan Museum of Art');
insert into books (name) values ('Full Speed (À toute vitesse)');
insert into books (name) values ('Assassination');
insert into books (name) values ('Double Impact');
insert into books (name) values ('Clifford');
insert into books (name) values ('Soldier of Orange (a.k.a. Survival Run) (Soldaat van Oranje)');
insert into books (name) values ('In Her Shoes');
insert into books (name) values ('The Last Station');
insert into books (name) values ('12 Rounds 2: Reloaded');
insert into books (name) values ('Love Steaks');
insert into books (name) values ('Northern Soul');
insert into books (name) values ('Darkness');
insert into books (name) values ('Lady Takes a Chance, A');
insert into books (name) values ('Long Riders, The');
insert into books (name) values ('I Am Dina');
insert into books (name) values ('Funny Thing Happened on the Way to the Forum, A');

-- People data
insert into people (name, country_id) values ('Bancroft', 'CN');
insert into people (name, country_id) values ('Clo', 'PL');
insert into people (name, country_id) values ('Marga', 'PK');
insert into people (name, country_id) values ('Giordano', 'CN');
insert into people (name, country_id) values ('Prinz', 'ID');
insert into people (name, country_id) values ('Rosmunda', 'NO');
insert into people (name, country_id) values ('Brad', 'RU');
insert into people (name, country_id) values ('Jess', 'GR');
insert into people (name, country_id) values ('Harcourt', 'FI');
insert into people (name, country_id) values ('Percy', 'IE');
insert into people (name, country_id) values ('Elinore', 'CZ');
insert into people (name, country_id) values ('Anson', 'PL');
insert into people (name, country_id) values ('Vonni', 'ID');
insert into people (name, country_id) values ('Leonore', 'YE');
insert into people (name, country_id) values ('Lynna', 'PT');
insert into people (name, country_id) values ('Perry', 'PH');
insert into people (name, country_id) values ('Lemmie', 'SE');
insert into people (name, country_id) values ('Elysee', 'SE');
insert into people (name, country_id) values ('Elianora', 'SE');
insert into people (name, country_id) values ('Carla', 'PH');
insert into people (name, country_id) values ('Betteanne', 'IL');
insert into people (name, country_id) values ('Brannon', 'PE');
insert into people (name, country_id) values ('Arliene', 'GR');
insert into people (name, country_id) values ('Dara', 'JP');
insert into people (name, country_id) values ('Alfie', 'FM');
insert into people (name, country_id) values ('Erminia', 'GT');
insert into people (name, country_id) values ('Beltran', 'SN');
insert into people (name, country_id) values ('Arron', 'IS');
insert into people (name, country_id) values ('Gasparo', 'ID');
insert into people (name, country_id) values ('Philippine', 'LV');
insert into people (name, country_id) values ('Ros', 'SE');
insert into people (name, country_id) values ('Willetta', 'PS');
insert into people (name, country_id) values ('Margie', 'BY');
insert into people (name, country_id) values ('Sigismund', 'MY');
insert into people (name, country_id) values ('Cristina', 'CM');
insert into people (name, country_id) values ('Galven', 'SY');
insert into people (name, country_id) values ('Dunn', 'UA');
insert into people (name, country_id) values ('Bartholomeo', 'CO');
insert into people (name, country_id) values ('Vernor', 'PL');
insert into people (name, country_id) values ('Nate', 'IE');
insert into people (name, country_id) values ('Roseline', 'NE');
insert into people (name, country_id) values ('Derby', 'NI');
insert into people (name, country_id) values ('Layney', 'CZ');
insert into people (name, country_id) values ('Lib', 'AF');
insert into people (name, country_id) values ('Rea', 'DO');
insert into people (name, country_id) values ('Freddi', 'CN');
insert into people (name, country_id) values ('Maggee', 'CN');
insert into people (name, country_id) values ('Kurt', 'BR');
insert into people (name, country_id) values ('Antonietta', 'BR');
insert into people (name, country_id) values ('Anne', 'BD');
insert into people (name, country_id) values ('Wolfie', 'FR');
insert into people (name, country_id) values ('Rivy', 'RU');
insert into people (name, country_id) values ('Ignacio', 'PT');
insert into people (name, country_id) values ('Cullan', 'CO');
insert into people (name, country_id) values ('Thorin', 'PT');
insert into people (name, country_id) values ('Adlai', 'PH');
insert into people (name, country_id) values ('Sabra', 'RS');
insert into people (name, country_id) values ('Alvis', 'CN');
insert into people (name, country_id) values ('Christiane', 'NO');
insert into people (name, country_id) values ('Patricio', 'RU');
insert into people (name, country_id) values ('Denny', 'FR');
insert into people (name, country_id) values ('Sigfried', 'DO');
insert into people (name, country_id) values ('Anthe', 'FR');
insert into people (name, country_id) values ('Ophelie', 'DO');
insert into people (name, country_id) values ('Aleece', 'MX');
insert into people (name, country_id) values ('Mohammed', 'RU');
insert into people (name, country_id) values ('Franky', 'YE');
insert into people (name, country_id) values ('Giraud', 'PE');
insert into people (name, country_id) values ('Lari', 'GQ');
insert into people (name, country_id) values ('Mahalia', 'CN');
insert into people (name, country_id) values ('Anders', 'FM');
insert into people (name, country_id) values ('Chandra', 'IT');
insert into people (name, country_id) values ('Philly', 'RU');
insert into people (name, country_id) values ('Addy', 'BY');
insert into people (name, country_id) values ('Jada', 'PH');
insert into people (name, country_id) values ('Lexi', 'MT');
insert into people (name, country_id) values ('Gunter', 'MR');
insert into people (name, country_id) values ('Zena', 'ID');
insert into people (name, country_id) values ('Cal', 'MT');
insert into people (name, country_id) values ('Ollie', 'CN');
insert into people (name, country_id) values ('Luz', 'TJ');
insert into people (name, country_id) values ('Roger', 'CN');
insert into people (name, country_id) values ('Annette', 'BR');
insert into people (name, country_id) values ('Thurston', 'ID');
insert into people (name, country_id) values ('Keefe', 'ID');
insert into people (name, country_id) values ('Adan', 'CN');
insert into people (name, country_id) values ('Gusti', 'CN');
insert into people (name, country_id) values ('Dora', 'US');
insert into people (name, country_id) values ('Annabel', 'FR');
insert into people (name, country_id) values ('Keary', 'CA');
insert into people (name, country_id) values ('Doloritas', 'KE');
insert into people (name, country_id) values ('Haley', 'CI');
insert into people (name, country_id) values ('Brooke', 'PL');
insert into people (name, country_id) values ('Nikolaos', 'ID');
insert into people (name, country_id) values ('Rafaelita', 'AF');
insert into people (name, country_id) values ('Annamarie', 'SE');
insert into people (name, country_id) values ('Nowell', 'CN');
insert into people (name, country_id) values ('Mil', 'TH');
insert into people (name, country_id) values ('Annadiane', 'BR');
insert into people (name, country_id) values ('Saunders', 'CN');

-- Authors-books data
insert into author_books (author_id, book_id) values (13, 2);
insert into author_books (author_id, book_id) values (3, 18);
insert into author_books (author_id, book_id) values (1, 10);
insert into author_books (author_id, book_id) values (28, 17);
insert into author_books (author_id, book_id) values (1, 13);
insert into author_books (author_id, book_id) values (27, 20);
insert into author_books (author_id, book_id) values (24, 4);
insert into author_books (author_id, book_id) values (14, 5);
insert into author_books (author_id, book_id) values (20, 9);
insert into author_books (author_id, book_id) values (2, 2);
insert into author_books (author_id, book_id) values (19, 1);
insert into author_books (author_id, book_id) values (8, 4);
insert into author_books (author_id, book_id) values (21, 15);
insert into author_books (author_id, book_id) values (18, 12);
insert into author_books (author_id, book_id) values (18, 18);
insert into author_books (author_id, book_id) values (24, 2);
insert into author_books (author_id, book_id) values (29, 15);
insert into author_books (author_id, book_id) values (27, 1);
insert into author_books (author_id, book_id) values (7, 2);
insert into author_books (author_id, book_id) values (12, 2);
insert into author_books (author_id, book_id) values (24, 9);
insert into author_books (author_id, book_id) values (23, 17);
insert into author_books (author_id, book_id) values (23, 7);
insert into author_books (author_id, book_id) values (19, 4);
insert into author_books (author_id, book_id) values (12, 8);
insert into author_books (author_id, book_id) values (25, 13);
insert into author_books (author_id, book_id) values (4, 7);
insert into author_books (author_id, book_id) values (26, 7);
insert into author_books (author_id, book_id) values (11, 16);
insert into author_books (author_id, book_id) values (12, 4);
insert into author_books (author_id, book_id) values (24, 8);
insert into author_books (author_id, book_id) values (12, 14);
insert into author_books (author_id, book_id) values (13, 1);
insert into author_books (author_id, book_id) values (25, 19);
insert into author_books (author_id, book_id) values (18, 10);
insert into author_books (author_id, book_id) values (15, 13);
insert into author_books (author_id, book_id) values (17, 16);
insert into author_books (author_id, book_id) values (22, 1);
insert into author_books (author_id, book_id) values (4, 19);
insert into author_books (author_id, book_id) values (9, 4);
insert into author_books (author_id, book_id) values (17, 14);
insert into author_books (author_id, book_id) values (7, 11);
insert into author_books (author_id, book_id) values (19, 5);
insert into author_books (author_id, book_id) values (17, 17);
insert into author_books (author_id, book_id) values (10, 4);
insert into author_books (author_id, book_id) values (8, 20);
insert into author_books (author_id, book_id) values (9, 7);
insert into author_books (author_id, book_id) values (24, 1);
insert into author_books (author_id, book_id) values (6, 5);
insert into author_books (author_id, book_id) values (6, 6);

-- Book rents data
insert into book_rents (book_id, person_id) values (13, 74);
insert into book_rents (book_id, person_id) values (13, 78);
insert into book_rents (book_id, person_id) values (17, 25);
insert into book_rents (book_id, person_id) values (4, 3);
insert into book_rents (book_id, person_id) values (13, 67);
insert into book_rents (book_id, person_id) values (4, 22);
insert into book_rents (book_id, person_id) values (1, 43);
insert into book_rents (book_id, person_id) values (2, 54);
insert into book_rents (book_id, person_id) values (9, 61);
insert into book_rents (book_id, person_id) values (11, 30);
insert into book_rents (book_id, person_id) values (16, 14);
insert into book_rents (book_id, person_id) values (13, 59);
insert into book_rents (book_id, person_id) values (1, 15);
insert into book_rents (book_id, person_id) values (18, 32);
insert into book_rents (book_id, person_id) values (19, 2);
insert into book_rents (book_id, person_id) values (17, 57);
insert into book_rents (book_id, person_id) values (15, 4);
insert into book_rents (book_id, person_id) values (12, 65);
insert into book_rents (book_id, person_id) values (14, 72);
insert into book_rents (book_id, person_id) values (1, 62);
insert into book_rents (book_id, person_id) values (18, 32);
insert into book_rents (book_id, person_id) values (1, 91);
insert into book_rents (book_id, person_id) values (11, 85);
insert into book_rents (book_id, person_id) values (1, 31);
insert into book_rents (book_id, person_id) values (6, 14);
insert into book_rents (book_id, person_id) values (17, 30);
insert into book_rents (book_id, person_id) values (9, 94);
insert into book_rents (book_id, person_id) values (16, 16);
insert into book_rents (book_id, person_id) values (15, 11);
insert into book_rents (book_id, person_id) values (14, 41);
insert into book_rents (book_id, person_id) values (7, 70);
insert into book_rents (book_id, person_id) values (14, 49);
insert into book_rents (book_id, person_id) values (16, 85);
insert into book_rents (book_id, person_id) values (3, 39);
insert into book_rents (book_id, person_id) values (8, 27);
insert into book_rents (book_id, person_id) values (16, 60);
insert into book_rents (book_id, person_id) values (15, 74);
insert into book_rents (book_id, person_id) values (3, 48);
insert into book_rents (book_id, person_id) values (7, 56);
insert into book_rents (book_id, person_id) values (13, 40);
insert into book_rents (book_id, person_id) values (9, 49);
insert into book_rents (book_id, person_id) values (14, 37);
insert into book_rents (book_id, person_id) values (12, 15);
insert into book_rents (book_id, person_id) values (17, 52);
insert into book_rents (book_id, person_id) values (13, 67);
insert into book_rents (book_id, person_id) values (8, 85);
insert into book_rents (book_id, person_id) values (6, 21);
insert into book_rents (book_id, person_id) values (11, 9);
insert into book_rents (book_id, person_id) values (17, 46);
insert into book_rents (book_id, person_id) values (13, 23);
insert into book_rents (book_id, person_id) values (2, 40);
insert into book_rents (book_id, person_id) values (16, 5);
insert into book_rents (book_id, person_id) values (1, 22);
insert into book_rents (book_id, person_id) values (9, 28);
insert into book_rents (book_id, person_id) values (1, 29);
insert into book_rents (book_id, person_id) values (4, 55);
insert into book_rents (book_id, person_id) values (18, 39);
insert into book_rents (book_id, person_id) values (10, 45);
insert into book_rents (book_id, person_id) values (2, 17);
insert into book_rents (book_id, person_id) values (12, 77);
insert into book_rents (book_id, person_id) values (19, 99);
insert into book_rents (book_id, person_id) values (20, 11);
insert into book_rents (book_id, person_id) values (13, 58);
insert into book_rents (book_id, person_id) values (15, 91);
insert into book_rents (book_id, person_id) values (18, 47);
insert into book_rents (book_id, person_id) values (13, 88);
insert into book_rents (book_id, person_id) values (16, 38);
insert into book_rents (book_id, person_id) values (1, 56);
insert into book_rents (book_id, person_id) values (12, 5);
insert into book_rents (book_id, person_id) values (11, 34);
insert into book_rents (book_id, person_id) values (9, 38);
insert into book_rents (book_id, person_id) values (15, 5);
insert into book_rents (book_id, person_id) values (11, 4);
insert into book_rents (book_id, person_id) values (9, 48);
insert into book_rents (book_id, person_id) values (6, 32);
insert into book_rents (book_id, person_id) values (3, 8);
insert into book_rents (book_id, person_id) values (17, 66);
insert into book_rents (book_id, person_id) values (16, 79);
insert into book_rents (book_id, person_id) values (5, 50);
insert into book_rents (book_id, person_id) values (5, 91);
insert into book_rents (book_id, person_id) values (6, 55);
insert into book_rents (book_id, person_id) values (20, 10);
insert into book_rents (book_id, person_id) values (3, 59);
insert into book_rents (book_id, person_id) values (9, 59);
insert into book_rents (book_id, person_id) values (20, 71);
insert into book_rents (book_id, person_id) values (8, 36);
insert into book_rents (book_id, person_id) values (17, 62);
insert into book_rents (book_id, person_id) values (2, 1);
insert into book_rents (book_id, person_id) values (5, 76);
insert into book_rents (book_id, person_id) values (13, 88);
insert into book_rents (book_id, person_id) values (6, 33);
insert into book_rents (book_id, person_id) values (15, 13);
insert into book_rents (book_id, person_id) values (2, 67);
insert into book_rents (book_id, person_id) values (16, 86);
insert into book_rents (book_id, person_id) values (18, 16);
insert into book_rents (book_id, person_id) values (1, 93);
insert into book_rents (book_id, person_id) values (16, 6);
insert into book_rents (book_id, person_id) values (2, 58);
insert into book_rents (book_id, person_id) values (1, 95);
insert into book_rents (book_id, person_id) values (16, 48);
insert into book_rents (book_id, person_id) values (13, 24);
insert into book_rents (book_id, person_id) values (13, 89);
insert into book_rents (book_id, person_id) values (20, 54);
insert into book_rents (book_id, person_id) values (11, 68);
insert into book_rents (book_id, person_id) values (11, 3);
insert into book_rents (book_id, person_id) values (7, 37);
insert into book_rents (book_id, person_id) values (19, 76);
insert into book_rents (book_id, person_id) values (7, 41);
insert into book_rents (book_id, person_id) values (11, 42);
insert into book_rents (book_id, person_id) values (4, 31);
insert into book_rents (book_id, person_id) values (9, 50);
insert into book_rents (book_id, person_id) values (8, 78);
insert into book_rents (book_id, person_id) values (2, 12);
insert into book_rents (book_id, person_id) values (17, 68);
insert into book_rents (book_id, person_id) values (15, 39);
insert into book_rents (book_id, person_id) values (12, 37);
insert into book_rents (book_id, person_id) values (5, 30);
insert into book_rents (book_id, person_id) values (7, 47);
insert into book_rents (book_id, person_id) values (17, 5);
insert into book_rents (book_id, person_id) values (1, 68);
insert into book_rents (book_id, person_id) values (13, 88);
insert into book_rents (book_id, person_id) values (15, 86);
insert into book_rents (book_id, person_id) values (16, 73);
insert into book_rents (book_id, person_id) values (19, 11);
insert into book_rents (book_id, person_id) values (17, 89);
insert into book_rents (book_id, person_id) values (14, 23);
insert into book_rents (book_id, person_id) values (8, 22);
insert into book_rents (book_id, person_id) values (20, 54);
insert into book_rents (book_id, person_id) values (18, 64);
insert into book_rents (book_id, person_id) values (4, 50);
insert into book_rents (book_id, person_id) values (10, 40);
insert into book_rents (book_id, person_id) values (19, 53);
insert into book_rents (book_id, person_id) values (9, 64);
insert into book_rents (book_id, person_id) values (12, 21);
insert into book_rents (book_id, person_id) values (18, 84);
insert into book_rents (book_id, person_id) values (15, 57);
insert into book_rents (book_id, person_id) values (5, 71);
insert into book_rents (book_id, person_id) values (18, 63);
insert into book_rents (book_id, person_id) values (1, 49);
insert into book_rents (book_id, person_id) values (4, 97);
insert into book_rents (book_id, person_id) values (4, 93);
insert into book_rents (book_id, person_id) values (19, 98);
insert into book_rents (book_id, person_id) values (16, 29);
insert into book_rents (book_id, person_id) values (6, 78);
insert into book_rents (book_id, person_id) values (4, 35);
insert into book_rents (book_id, person_id) values (15, 83);
insert into book_rents (book_id, person_id) values (16, 92);
insert into book_rents (book_id, person_id) values (12, 61);
insert into book_rents (book_id, person_id) values (1, 37);
insert into book_rents (book_id, person_id) values (4, 77);
insert into book_rents (book_id, person_id) values (15, 78);
insert into book_rents (book_id, person_id) values (18, 89);
insert into book_rents (book_id, person_id) values (2, 15);
insert into book_rents (book_id, person_id) values (2, 13);
insert into book_rents (book_id, person_id) values (17, 7);
insert into book_rents (book_id, person_id) values (7, 64);
insert into book_rents (book_id, person_id) values (18, 83);
insert into book_rents (book_id, person_id) values (1, 81);
insert into book_rents (book_id, person_id) values (8, 24);
insert into book_rents (book_id, person_id) values (16, 55);
insert into book_rents (book_id, person_id) values (1, 81);
insert into book_rents (book_id, person_id) values (7, 59);
insert into book_rents (book_id, person_id) values (12, 39);
insert into book_rents (book_id, person_id) values (13, 34);
insert into book_rents (book_id, person_id) values (2, 99);
insert into book_rents (book_id, person_id) values (1, 69);
insert into book_rents (book_id, person_id) values (12, 39);
insert into book_rents (book_id, person_id) values (1, 17);
insert into book_rents (book_id, person_id) values (5, 61);
insert into book_rents (book_id, person_id) values (17, 77);
insert into book_rents (book_id, person_id) values (3, 5);
insert into book_rents (book_id, person_id) values (13, 21);
insert into book_rents (book_id, person_id) values (16, 21);
insert into book_rents (book_id, person_id) values (16, 96);
insert into book_rents (book_id, person_id) values (14, 60);
insert into book_rents (book_id, person_id) values (7, 8);
insert into book_rents (book_id, person_id) values (12, 31);
insert into book_rents (book_id, person_id) values (6, 71);
insert into book_rents (book_id, person_id) values (2, 19);
insert into book_rents (book_id, person_id) values (12, 74);
insert into book_rents (book_id, person_id) values (1, 81);
insert into book_rents (book_id, person_id) values (18, 28);
insert into book_rents (book_id, person_id) values (2, 24);
insert into book_rents (book_id, person_id) values (7, 92);
insert into book_rents (book_id, person_id) values (16, 85);
insert into book_rents (book_id, person_id) values (12, 91);
insert into book_rents (book_id, person_id) values (20, 66);
insert into book_rents (book_id, person_id) values (5, 89);
insert into book_rents (book_id, person_id) values (10, 81);
insert into book_rents (book_id, person_id) values (12, 48);
insert into book_rents (book_id, person_id) values (1, 24);
insert into book_rents (book_id, person_id) values (14, 15);
insert into book_rents (book_id, person_id) values (11, 86);
insert into book_rents (book_id, person_id) values (17, 61);
insert into book_rents (book_id, person_id) values (16, 94);
insert into book_rents (book_id, person_id) values (18, 72);
insert into book_rents (book_id, person_id) values (12, 9);
insert into book_rents (book_id, person_id) values (18, 9);
insert into book_rents (book_id, person_id) values (19, 70);
insert into book_rents (book_id, person_id) values (9, 83);
insert into book_rents (book_id, person_id) values (4, 53);
insert into book_rents (book_id, person_id) values (7, 74);
insert into book_rents (book_id, person_id) values (20, 84);
insert into book_rents (book_id, person_id) values (6, 100);
insert into book_rents (book_id, person_id) values (5, 58);
insert into book_rents (book_id, person_id) values (6, 61);
insert into book_rents (book_id, person_id) values (18, 98);
insert into book_rents (book_id, person_id) values (10, 19);
insert into book_rents (book_id, person_id) values (14, 81);
insert into book_rents (book_id, person_id) values (18, 37);
insert into book_rents (book_id, person_id) values (13, 11);
insert into book_rents (book_id, person_id) values (7, 67);
insert into book_rents (book_id, person_id) values (3, 8);
insert into book_rents (book_id, person_id) values (20, 91);
insert into book_rents (book_id, person_id) values (13, 64);
insert into book_rents (book_id, person_id) values (16, 59);
insert into book_rents (book_id, person_id) values (11, 85);
insert into book_rents (book_id, person_id) values (13, 29);
insert into book_rents (book_id, person_id) values (7, 91);
insert into book_rents (book_id, person_id) values (3, 60);
insert into book_rents (book_id, person_id) values (19, 26);
insert into book_rents (book_id, person_id) values (5, 97);
insert into book_rents (book_id, person_id) values (12, 23);
insert into book_rents (book_id, person_id) values (18, 39);
insert into book_rents (book_id, person_id) values (1, 16);
insert into book_rents (book_id, person_id) values (17, 88);
insert into book_rents (book_id, person_id) values (10, 49);
insert into book_rents (book_id, person_id) values (16, 24);
insert into book_rents (book_id, person_id) values (16, 51);
insert into book_rents (book_id, person_id) values (2, 55);
insert into book_rents (book_id, person_id) values (17, 97);
insert into book_rents (book_id, person_id) values (20, 73);
insert into book_rents (book_id, person_id) values (20, 64);
insert into book_rents (book_id, person_id) values (18, 73);
insert into book_rents (book_id, person_id) values (10, 22);
insert into book_rents (book_id, person_id) values (19, 5);
insert into book_rents (book_id, person_id) values (11, 80);
insert into book_rents (book_id, person_id) values (7, 16);
insert into book_rents (book_id, person_id) values (3, 6);
insert into book_rents (book_id, person_id) values (20, 82);
insert into book_rents (book_id, person_id) values (1, 9);
insert into book_rents (book_id, person_id) values (8, 68);
insert into book_rents (book_id, person_id) values (8, 33);
insert into book_rents (book_id, person_id) values (9, 69);
insert into book_rents (book_id, person_id) values (2, 43);
insert into book_rents (book_id, person_id) values (16, 42);
insert into book_rents (book_id, person_id) values (5, 84);
insert into book_rents (book_id, person_id) values (15, 95);
insert into book_rents (book_id, person_id) values (8, 95);
insert into book_rents (book_id, person_id) values (4, 73);
